### ISSUE TITLE
  How to reduce the time of post-processing?

### ISSUE THREAD

**Issue by guoguangchao** [biubug6/Pytorch_Retinaface#11]
Although the network forward time only about 5ms, But the post-processing time on my laptop is up to 150 ms. 
The main time-consuming places are 98 to 102 lines in detect.py,  generating the prior box take up a lot of time, What can we do to reduce it? thanks

**Comment by mooss** [comment]
It looks like all the priorboxes are created, even the ones who are associated with an anchor without a match, then all the locations and all the priorboxes are send to decode and it's only later that the uninteresting predictions are discarded (line 114 through 124).

I think it's possible to do the opposite, first discard uninteresting predictions, then generate only the priorboxes corresponding to the interesting propositions and then decode them. This might provide the speedup you seek.

**Comment by xsacha** [comment]
Personally, I run the code in C++ and have my own code that generates prior boxes once and caches the result.

```C++
    std::vector<std::array<float, 3>> generateDefaultBoxRetina(int width, int height, bool eight)
    {
        std::vector<std::array<float, 3>> boxes;

        // Perform pyramid boxes
        std::vector<int> feature_map_sizes = eight ? std::vector<int>{8, 16, 32} : std::vector<int>{16, 32, 64};
        std::vector<std::vector<int>> min_sizes = {{16, 32}, {64, 128}, {256, 512}};
        for (int e = 0; e < feature_map_sizes.size(); ++e)
        {
            auto fmap = feature_map_sizes.at(e);
            const int maxH = (int)std::ceil((float)height / (float)fmap);
            const int maxW = (int)std::ceil((float)width / (float)fmap);
            for (int h = 0; h < maxH; ++h)
            {
                for (int w = 0; w < maxW; ++w)
                {
                    for (const auto &min_size : min_sizes.at(e))
                    {
                        const float sz = (float)min_size;
                        auto addBox = [&boxes, &sz, &w, &h, &fmap](float xo, float yo) {
                            const float cx = (w + xo) * fmap;
                            const float cy = (h + yo) * fmap;
                            boxes.push_back({cx, cy, sz});
                        };
                        addBox(0.5f, 0.5f);
                    }
                }
            }
        }

        return boxes;
    }
```

**Comment by guoguangchao** [comment]
@xsacha @mooss Thank you for your answer. It's very helpful to me.
