### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by mehrdadazizi72** [biubug6/Pytorch_Retinaface#12]
@biubug6 Hi, I feed when I try to use detect.py, return this error: 

 File "...../Pytorch_Retinaface/utils/box_utils.py", line 214, in decode
    priors[:, :2] + loc[:, :2] * variances[0] * priors[:, 2:],
RuntimeError: The size of tensor a (2688) must match the size of tensor b (2470) at non-singleton dimension 0

**Comment by biubug6** [comment]
It is curious. You may make a wrong inappropriate change that  causes the mistake.

**Comment by mehrdadazizi72** [comment]
@biubug6 it's my mistake! I'm using python2 instead of python3
