### ISSUE TITLE
valueError : zero-size array to reductton operation minimum whtch has no identity

### ISSUE THREAD

**Issue by Wblossom** [biubug6/Pytorch_Retinaface#139]
when I ran python test_widerface.py --trained_model weights/mobilenet0.25 --network mobile0.25, I met the following problem, does anyone know how to solve it?
![image](https://user-images.githubusercontent.com/73222086/99048557-ae24ba80-25d0-11eb-904f-9c7f1110cb34.png)

**Comment by pinery-sls** [comment]
> when I ran python test_widerface.py --trained_model weights/mobilenet0.25 --network mobile0.25, I met the following problem, does anyone know how to solve it? ![image](https://user-images.githubusercontent.com/73222086/99048557-ae24ba80-25d0-11eb-904f-9c7f1110cb34.png)

me too. How to solve it?
