### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by mehrdadazizi72** [biubug6/Pytorch_Retinaface#15]
@biubug6 Hi, thanks for your great work.
I tested to pictures and get strange results.
these are inputs:
![12](https://user-images.githubusercontent.com/38887451/66704596-35e32a00-ed2a-11e9-8a63-f115e3d3d6a4.jpg)
![62072401121361486](https://user-images.githubusercontent.com/38887451/66704597-35e32a00-ed2a-11e9-83bd-f4de954cd2de.jpg)

and these are outputs:

![1570897339 4553294](https://user-images.githubusercontent.com/38887451/66704608-4dbaae00-ed2a-11e9-979c-4e3bbe521e96.jpg)
![1570896991 89142](https://user-images.githubusercontent.com/38887451/66704611-56ab7f80-ed2a-11e9-96c8-796540a7a726.jpg)

the first image has more score compare to some faces in second images.
is it right?

**Comment by biubug6** [comment]
Due to limited expression ability, small networks may exist this problem with few images. Resnet50 as backbone could output better results.
