### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by yjhuasheng** [biubug6/Pytorch_Retinaface#17]
Hi, when I run the test_wilderface.py, return the valueError
 File "test_widerface.py", line 107, in <module>
    im_size_min = np.min(im_shape[0:2])
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 2746, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by AndrewSoul** [comment]
> Hi, when I run the test_wilderface.py, return the valueError
> File "test_widerface.py", line 107, in
> im_size_min = np.min(im_shape[0:2])
> File "<**array_function** internals>", line 6, in amin
> File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 2746, in amin
> keepdims=keepdims, initial=initial, where=where)
> File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
> return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> ValueError: zero-size array to reduction operation minimum which has no identity

I have the same problem. How did you fix it?

**Comment by biubug6** [comment]
You get the image_raw of "None"  Which causes im_shape of "empty tuple" . Maybe you need to check your test data path.

**Comment by AndrewSoul** [comment]
> You get the image_raw of "None" Which causes im_shape of "empty tuple" . Maybe you need to check your test data path.

Thanks.

**Comment by pinery-sls** [comment]
me too. How to solve it?

**Comment by pinery-sls** [comment]
> > Hi, when I run the test_wilderface.py, return the valueError
> > File "test_widerface.py", line 107, in
> > im_size_min = np.min(im_shape[0:2])
> > File "<**array_function** internals>", line 6, in amin
> > File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 2746, in amin
> > keepdims=keepdims, initial=initial, where=where)
> > File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
> > return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> > ValueError: zero-size array to reduction operation minimum which has no identity
> 
> I have the same problem. How did you fix it?

me too. How to solve it????
