### ISSUE TITLE
an error in data augment?

### ISSUE THREAD

**Issue by Keysmis** [biubug6/Pytorch_Retinaface#18]
I think you have a mistake in data_augment.py preproc ruction.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/9586803/66903894-caed6800-f035-11e9-8def-af057d21ad30.png">
maybe you should multiply the resize_size??

**Comment by hegc** [comment]
boxes_t[:, 0::2] = boxes_t[:, 0::2]  * (self.img_dim / width) / self.img_dim, so the self.img_dim is reduced.

**Comment by biubug6** [comment]
boxes_t[:, 0::2] = boxes_t[:, 0::2]/width *self.img_dim is equal to boxes_t[:, 0::2] = (boxes_t[:, 0::2]/width) * self.img_dim . You may have a wrong understanding on that.

**Comment by SnowRipple** [comment]
@biubug6 
A little of-topic.. Can you described the meaning behind "min_sizes" and "steps" in config please? What would be the reason for modifying them?

**Comment by biubug6** [comment]
"min_sizes"  is anchor size on different scales, "steps" is downsampling rate of feature map.  I don't modify them?

**Comment by Keysmis** [comment]
@biubug6  yeah, but you have missed the self.img_dim in your code。。。

**Comment by Keysmis** [comment]
![image](https://user-images.githubusercontent.com/9586803/66915122-d6975980-f04a-11e9-95de-9cdcb208880f.png)
so the picture's code is right.... you have regulated the labels?

**Comment by SnowRipple** [comment]
@hegc  Sorry. maybe I'm missing something but both boxes and landmarks are normalized with width and height of the image **before** resizing, why? 
Since height and width change after resizing shouldn't they be normalized with width and height **after** resizing?
