### ISSUE TITLE
Loss weighting

### ISSUE THREAD

**Issue by siyiding1216** [biubug6/Pytorch_Retinaface#19]
In RetinaFace paper, it has 4 losses and has different weights for each, roughly has a ratio of 65:25:10:1. 
Understood that you did not put the dense regression loss in implementation. and I saw a  2:1:1 in the config, just wonder is this the findout of your cross validation to balance the three losses?
Did you test other ratios?

**Comment by biubug6** [comment]
Parameters in the paper can get good results in  the author's experiment based on mxnet. Some differences in implementation details lead to some differences in parameters.  We often give more weight to the information we pay more attention to.
