### ISSUE TITLE
performance on oriented images

### ISSUE THREAD

**Issue by DecentMakeover** [biubug6/Pytorch_Retinaface#20]
Thanks for sharing your work.

I wanted to know your thoughts on how will retinaface perform on rotated face images/ face at weird angles?
When i tested it the result is not very good.

Moreover, 
How could i use the landmarks information to maybe align the image?

Thanks in advance.

**Comment by biubug6** [comment]
There is no special setting for rotating face in the network. If you want to get good results, you need to add more rotating faces to your training.

**Comment by DecentMakeover** [comment]
Okay, Thanks for the response.

**Comment by jiagh2010** [comment]
Do you have a pre trained model？@biubug6

**Comment by biubug6** [comment]
Pretrain model and trained model are put in google cloud and baidu cloud. You can refer to Training in readme.md
