### ISSUE TITLE
为什么classnum=2呢？不是只有一个类别就是脸吗？

### ISSUE THREAD

**Issue by zyxingzou** [biubug6/Pytorch_Retinaface#28]
1.为什么classnum=2呢？不是只有一个类别就是脸吗？

2.wider_face.py 里，67,68行 
if (annotation[0, 4]<0):
      annotation[0, 14] = -1
为什么要等于 -1 呢？

望解惑，谢谢!

**Comment by zyxingzou** [comment]
还有就是train.py 里面 94行
 dataset = WiderFaceDetection( training_dataset,preproc(img_dim, rgb_mean))
如果，preproc = None 就报错

**Comment by biubug6** [comment]
1. 是不是人脸即是一个二项分布 (人脸, 非人脸)
2.if (annotation[0, 4]<0):代表关键点信息不可用, 后面就不会对这个框回归关键点信息.
3.WiderFaceDetection( training_dataset,preproc(img_dim, rgb_mean))详情可以详细看demo.

**Comment by zyxingzou** [comment]
非常感谢！

**Comment by DuckJ** [comment]
[这里](https://github.com/biubug6/Pytorch_Retinaface/blob/master/layers/modules/multibox_loss.py#L80)判断label>0 才会算landmark loss是吧，multibox_loss里面有个bkg_label,这个应该没起到作用吧
标签为-1的人脸其实也是人脸，这个在训练中怎么起作用的，能解释一下吗？有点糊涂
@biubug6 @zyxingzou

**Comment by DuckJ** [comment]
这里的人脸label标记为1和-1，人脸分为了两类，训练过程没问题吗

**Comment by DuckJ** [comment]
明白了，求loss时候先用到了-1 的label求landmark，然后把标签非0的都转化为了1，即两种人脸都归类为一种人脸，然后去给loss排序什么
