### ISSUE TITLE
About the meaning of conf elements.

### ISSUE THREAD

**Issue by AndrewSoul** [biubug6/Pytorch_Retinaface#33]
Hi. The shape of conf is (N, boxes_num, 2).  (N, boxes_num, 1:2) is the confidence of face classification. May I ask,  is (N, boxes_num, 0:1)  the confidence of not a face classification? Thanks.

**Comment by biubug6** [comment]
When testing,  conf[N, boxes_num, 1:2] =1 - conf[N, boxes_num, 0:1].

**Comment by AndrewSoul** [comment]
> When testing, conf[N, boxes_num, 1:2] =1 - conf[N, boxes_num, 0:1].

Thanks.
