### ISSUE TITLE
What are the proprties for get the coordinate to crop the images ?

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [biubug6/Pytorch_Retinaface#35]
@biubug6 
for the code, I find the crop coordinate but it not properly cropping,

ex:

                x = int(b[0])
                y = int(b[1])
                w = int(b[2])
                h = int(b[3])

                crop_img = img_raw[y:y+h,x:x+w]

please provide the coordinate for cropping he face

**Comment by biubug6** [comment]
You can refer to "_crop()" in https://github.com/biubug6/Pytorch_Retinaface/blob/master/data/data_augment.py for detials.
ps: It would calculate iou between box and crop_img.

**Comment by deepconsc** [comment]
@NarasimmanSaravana1994 

rectangle is added as following:

`
cv2_imshow(cv2.rectangle(im,(x,y),(x+w,y+h),(0,255,0),2))
`

I'd suggest numpy-approach for cropping, as:

`crop_img = raw_img[y:y+h, x:x+w]
`
In **dets** object, we have b[0],b[1],b[2],b[3], where **b[1], b[3]** are **y, y+h**, and **b[0], b[2]** are **x,x+w**

Therefore, cropping goes as:

`
cropped = img_raw[b[1]:b[3], b[0]:b[2]]
`

Works like a charm!
