### ISSUE TITLE
wrong with pre-train model

### ISSUE THREAD

**Issue by jayyoung0802** [biubug6/Pytorch_Retinaface#46]
There is a problem on the mobilenetV1X0.25_pretrain.tar, Can you update the download link?Thanks

**Comment by biubug6** [comment]
You can clone newest project,  then
```Shell
git reset --hard f7e3515afec5b036df2ed15e745f6385e3d81770
```
You will get "model_best.pth.tar" which is mobilenetV1X0.25_pretrain.tar.

**Comment by jayyoung0802** [comment]
> You can clone newest project, then
> 
> ```shell
> git reset --hard f7e3515afec5b036df2ed15e745f6385e3d81770
> ```
> 
> You will get "model_best.pth.tar" which is mobilenetV1X0.25_pretrain.tar.

thanks,it works
