### ISSUE TITLE
About processing video

### ISSUE THREAD

**Issue by DoriHp** [biubug6/Pytorch_Retinaface#47]
Your work is amazing. I tried it on few sample images and it work well in term of both speed and accuracy. Then, I tried to modify it for addressing face detecting in video file, but the processing time for each frame was so long. Can you provide me code for running with video, or any suggestions about it?
This is what I tried ("txt" format for github's supporting):
[video.txt](https://github.com/biubug6/Pytorch_Retinaface/files/3917188/video.txt)

**Comment by vijeshkpaei** [comment]
Hi,
i have used your video.py file for live detection in usb (lap spec 4GB RAM) , i got 27 to 30 fps. Thanks for your file

**Comment by Arthur-CYS** [comment]
Hello, I would like to ask how did you solve this problem. thank you！
