### ISSUE TITLE
Prefers resize to trained dimensions

### ISSUE THREAD

**Issue by xsacha** [biubug6/Pytorch_Retinaface#5]
![image](https://user-images.githubusercontent.com/61218/65207605-735ee980-dad5-11e9-82b8-d4fb5cfaa584.png)
Graph is on PASCAL
retinaface: resize = 1
retinaface-2: resize = 1.5 (or resize close to 640px, same effect)

Just like FaceBoxes prefers minimum face size (13 px) @ trained size (1024 px), RetinaFace also prefers resize to trained size (640px).

Right now resize is hardcoded to 1. I also now get a better result on AFW/PASCAL/etc..

**Comment by biubug6** [comment]
When training, Retinaface and Faceboxes  all adopt multi-scale training methods(correspondingly resize scale 640 or 1024). Tests often yield good results.

**Comment by xsacha** [comment]
I recommend this code in general to calculate resize:
```Python
resize = 1
        resizedelta = 0.25
        while img.shape[0] * resize < (640.0 * (1 - resizedelta / 2) ):
            resize += resizedelta
        if resize != 1:
            img = cv2.resize(img, None, None, fx=resize, fy=resize, interpolation=cv2.INTER_LINEAR)
```

I use the same on FaceBoxes but 1024.0 instead.
