### ISSUE TITLE
PriorBox use much time

### ISSUE THREAD

**Issue by zhouyongxiu** [biubug6/Pytorch_Retinaface#74]
When I use model to detect images, I find it spend much time in PriorBox function, is there any method to solve it?

**Comment by brealisty** [comment]
> When I use model to detect images, I find it spend much time in PriorBox function, is there any method to solve it?

did u solve it? I met the same issue.

**Comment by xsacha** [comment]
You can pre-calculate the box per resolution.

**Comment by zhouyongxiu** [comment]
> You can pre-calculate the box per resolution.

thanks a lot

**Comment by GYC1996** [comment]
> You can pre-calculate the box per resolution.

when I remove the prior box, but the cost time doesn't change

**Comment by Wblossom** [comment]
> You can pre-calculate the box per resolution.

Hi, can you tell more details? Thanks.

**Comment by Wblossom** [comment]
> > You can pre-calculate the box per resolution.
> 
> when I remove the prior box, but the cost time doesn't change

Hi, have you solved it?
