### ISSUE TITLE
What is a resume net? Can someone please elaborate?

### ISSUE THREAD

**Issue by neelabh17** [biubug6/Pytorch_Retinaface#75]

**Comment by xsacha** [comment]
The model that you resume training from (i.e. a checkpoint).

**Comment by watertianyi** [comment]
@xsacha I found resume_epoch
This is the set epoch. In the code, instead of starting from zero in the for loop, training starts from resume_epoch. Is this to start training from the node? Doesn’t it need to freeze some parameters?

**Comment by xsacha** [comment]
You have to specify which epoch you are on for your resume net if you are resuming from a checkpoint.
