### ISSUE TITLE
the Inference time is too long

### ISSUE THREAD

**Issue by gosser123** [biubug6/Pytorch_Retinaface#77]
I use detect.py to infer some images，Most pictures are about 500 * 300 in size，but the inference time is too long, my GPU is GTX1660,  the mobile0.25 net forward time is mostly 0.02s,  but the inference time of  a few pictures  is more than 0.2s .  And the resnet50 net forward time is mostly between 0.03s and 2.2s, even I get error:CUDA out of memory.  I don't know where is wrong, could you help me?

**Comment by gosser123** [comment]
chanege cudnn.benchmark to False

**Comment by GYC1996** [comment]
when I remove the prior box forward, but the cost time still
