### ISSUE TITLE
retinaface (resnet50) in tensorrt

### ISSUE THREAD

**Issue by wang-xinyu** [biubug6/Pytorch_Retinaface#89]
Hi @biubug6 ,

Thanks for your remarkable work, just to let you know that there is a TensorRT implemention of RetinaFace (resnet50) based on your pytorch implementation. And got the following fps test on TX2 and GTX1080.

| Models | Device | BatchSize | Mode | Input Shape(HxW) | FPS |
|-|-|:-:|:-:|:-:|:-:|
| RetinaFace(resnet50) | TX2 | 1 | FP16 | 384x640 | 15 |
| RetinaFace(resnet50) | Xeon E5-2620/GTX1080 | 1 | FP32 | 928x1600 | 15 |

FPS test including inference and nms time, excluding image preprocess time.

The link is
[https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface).

And it would be my pleasure if you added this link on your readme.

regards,
Xinyu

**Comment by biubug6** [comment]
Thank you for your excellent work! I will add this link on my readme.
