### ISSUE TITLE
Worse performance on windows than Ubuntu

### ISSUE THREAD

**Issue by Arki99** [biubug6/Pytorch_Retinaface#97]
I'm getting around 20fps on windows but 60fps on Ubuntu when I used the mobilenet pretrained weights. 
Both windows and Ubuntu use: 
-  CUDA 10.1
- pytorch 1.4

PC specs:
- intel i7
- 8 gb ram
- gtx 970m

Not sure why this is happening.

**Comment by xsacha** [comment]
Windows is always slower when using the 'WDDM' driver because Windows takes control of the GPU.

To get optimal performance on Windows, you must use the 'TCC' driver and bypass Windows UI. This requires a Titan, Quadro or Tesla card.
